apiVersion: v1
kind: Service
metadata:
  name: anomaly
  labels:
    app: anomaly
spec:
  selector:
    app: anomaly
  ports:
    - name: http-metrics
      port: 8001
      targetPort: 8001
  type: ClusterIP
