apiVersion: v1
kind: Service
metadata:
  name: exporter-site-b
  labels:
    app: exporter-site-b
spec:
  selector:
    app: exporter-site-b
  ports:
    - name: http-metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP
