apiVersion: v1
kind: Service
metadata:
  name: exporter
  namespace: iamakamen-dev
spec:
  selector:
    app: dtms-exporter
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
  