apiVersion: v1
kind: Service
metadata:
  name: freshness
  labels:
    app: dtms-freshness
spec:
  selector:
    app: dtms-freshness
  ports:
    - name: http-metrics
      port: 8004
      targetPort: 8004
  type: ClusterIP
