apiVersion: v1
kind: Service
metadata:
  name: dtms-spark-exporter
  labels:
    app: dtms-spark-exporter
spec:
  selector:
    app: dtms-spark-exporter
  ports:
    - name: metrics
      port: 8002
      targetPort: 8002
  type: ClusterIP
